<?php

use Drupal\taxonomy\TermInterface;

/**
 * Implements hook_entity_presave().
 * 
 */
function taxonomy_diff_ui_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity instanceof TermInterface) {
    $uid = \Drupal::currentUser()->id();
    $entity->setRevisionUserId($uid);
    $entity->setRevisionCreationTime(\Drupal::time()->getRequestTime());
    $entity->setNewRevision(TRUE);
  }
}

/**
 * Implements hook_entity_type_alter()
 * 
 */
function taxonomy_diff_ui_entity_type_alter(array &$entity_types) {
  
  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  
  // Set the revision link.
  $entity_types['taxonomy_term']->setLinkTemplate('revision', '/taxonomy/term/{taxonomy_term}/revisions/{taxonomy_term_revision}/view');
}